- name: package installation on hosts
  hosts: all
  become: yes
  tasks:
    - name: install packages
      package:
        name: 
          - apache2
          - nginx
          - mariadb-server
          - tree
        state: present